defaults:
  - embeddings: word2vec-custom
  - optimizer: adam
  - override hydra/launcher: joblib
  - _self_

data:
  path: "reviews_Cell_Phones_and_Accessories_5.json.txt"

model:
  batch_size: 50
  ortho_reg: 0.2
  aspects_number: 25
  epochs: 1
  negative_samples: 5
  max_len: 201
  log_progress_steps: 1000

hydra:
  job:
    config:
      override_dirname:
        exclude_keys:
          - model.log_progress_steps
  sweep:
    dir: results/${data.path}/
    subdir: ${hydra.job.override_dirname}
  help:
    template:
      "This is the script for training ABAE reimplemented in PyTorch"